name: Deploy Website

on:
  push:
    branches:
      - main  # ou master, selon votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and deploy
        run: |
          npm install
          mkdir -p docs
          cp -r lightup/web/* docs/
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Deploying website"
          git push origin main:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
