name: Deploy Website

on:
  push:
    branches:
      - main  # ou master, selon votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Copy website files
        run: |
          mkdir -p docs
          cp -r lightup/web/* docs/

      - name: Commit and push changes
        run: |
          cd docs
          git init
          git add .
          git commit -m "Deploying website"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages
